# -- PROD DOCKER-COMPOSE --
version: "3"

services:
  db:
    container_name: wiki-db
    image: postgres:9-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wikijsrocks
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "15432:5432"

  adminer:
    container_name: wiki-adminer
    image: adminer:latest
    logging:
      driver: "none"
    ports:
      - "3001:8080"


  wiki:
    container_name: wiki-app
    image: wiki
    depends_on:
      - db
    ports:
      - "3000:3000"


volumes:
  db-data:
